apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 992382722451.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:cd361a7343a832dbe7c9a56296d04592acc248b2
        ports:
        - containerPort: 80
