apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 992382722451.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:8959d82cbd7d2319a33705ac3023f182fd2fa08e
        ports:
        - containerPort: 80
