apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 992382722451.dkr.ecr.us-east-1.amazonaws.com/shopping-site-main:cd361a7343a832dbe7c9a56296d04592acc248b2
        ports:
        - containerPort: 80

