apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 992382722451.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:a3b846008e14aa5f4c0ee6fd5ccd725d6981b8d7
        ports:
        - containerPort: 80
